added chakra/basic layout
alisajidcs/blog-with-ali pull request #1
Opened 2022-06-15 18:35 UTC by MajidAliKhanQuaid

2022-06-17 05:43 UTC, alisajidcs commented on components/Navbar.tsx
> +const NavLink = ({ children }: { children: ReactNode }) => (
Move this in a separate file
Create a folder navbar, put this file in index.tsx. And place all sub components in separate files in that folder

2022-06-17 05:46 UTC, alisajidcs commented on components/Navbar.tsx
> +          <Box>
move this a separate component <HomeIcon />

2022-06-17 05:47 UTC, alisajidcs commented on components/Navbar.tsx
> +          <Flex alignItems={'center'}>
Move this in a separate component <NavItems />

2022-06-17 05:47 UTC, alisajidcs commented on package.json
> +    "yarn": "^1.22.19"
Why do we need this?

2022-06-17 05:49 UTC, alisajidcs commented on package.json
> +    "add": "^2.0.6",
What is this for? I don't see any import for this?

2022-06-17 05:50 UTC, alisajidcs commented on package.json
> +    "@emotion/styled": "^11",
What is this for? I don't see any import for both of these..

2022-06-17 05:51 UTC, alisajidcs requested changes
I have suggested few tweaks. look into it.

2022-06-21 06:26 UTC, MajidAliKhanQuaid commented on package.json
> +    "@emotion/styled": "^11",
these are used by chakra

2022-06-21 06:26 UTC, MajidAliKhanQuaid commented on package.json
> +    "add": "^2.0.6",
these are REMOVED now

2022-06-21 06:26 UTC, MajidAliKhanQuaid commented on package.json
> +    "yarn": "^1.22.19"
these are REMOVED now

2022-06-21 06:57 UTC, MajidAliKhanQuaid commented on components/Navbar.tsx
> +          <Flex alignItems={'center'}>
Done

2022-06-21 06:57 UTC, MajidAliKhanQuaid commented on components/Navbar.tsx
> +          <Box>
Done

2022-08-01 20:53 UTC, alisajidcs approved these changes

2022-08-01 20:57 UTC, merged